name: Approved for Release
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@31ed2e38a71fa1a9e05e0b5a960e4548c304d1ef
        with:
          mode: exactly
          count: 1
          labels: "Release Approved :)"
